services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Afpa1234
    volumes:
      - ./data:/var/lib/mysql

  web:
    build: .
    ports:
      - 81:80
    volumes:
      - .:/var/www

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8080:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Afpa1234
    ports:
      - 27018:27017
    volumes:
      - ./sampledata.archive:/sampledata.archive

volumes:
  data:
    driver: local
